spring.application.name=disorder-spring

server.error.include-stacktrace=never
server.error.include-message=never

spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=${PGSSLMODE}&channelbind=${PGCHANNELBINDING}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
